# Basic
title: fuxin123
subtitle: CN
description: æ¬¢è¿~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ä¸»é¡µ
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ç‚¹å‡»å‰å¾€
#url: "https://fuxin123zz.gitee.io/"
url: "https://fuxin123.cn/"

# Comment
comment:
    # disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 6716375741
    # github: fuxin123z
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ad
    twitter:
    mail: 444216502@qq.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
  #  id: 1c713d75dd35db158055897db970c7ee
    id: 9256a33e84f0e765090e7b6475479ba2

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
    #id: xxxx
   # host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  starğŸ˜† åœ°å€ï¼š https://fuxin123z
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
  #  - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

plugins:
 - jekyll-sitemap    #jekyllçš„ç«™ç‚¹åœ°å›¾æ’ä»¶ï¼Œç”¨äºç”Ÿæˆç«™ç‚¹åœ°å›¾
 - jekyll-admin
